//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WEBAPI_SELECT_JSON.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_EMPLOYEE
    {
        public int ID { get; set; }
        public string EMPLOYEENAME { get; set; }
        public string EMPLOYEESURNAME { get; set; }
        public string EMPLOYEEAGE { get; set; }
        public string EMPLOYEEMAIL { get; set; }
    }
}
